name: cardless
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  animated_splash_screen: ^1.2.0
  awesome_dialog: ^2.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  qr_code_scanner: ^0.7.0
  shared_preferences: ^2.0.13
  syncfusion_flutter_barcodes: ^20.1.51

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
